Efreet: lib/efreet_xml.c File Reference
Home
News
About
Download
Main Page Files Modules Data Structures Index
Support
Contribute
Contact
Tracker
lib/efreet_xml.c File Reference
#include "Efreet.h"
#include "efreet_private.h"
Functions
const char * efreet_xml_attribute_get (Efreet_Xml *xml, const char *key)
Retrieves the value for the given attribute key.
void efreet_xml_del (Efreet_Xml *xml)
int efreet_xml_init (void)
Efreet_Xml * efreet_xml_new (const char *file)
int efreet_xml_shutdown (void)
Function Documentation
const char* efreet_xml_attribute_get (Efreet_Xml * xml, const char * key)
Retrieves the value for the given attribute key.
Parameters:
xml,: The xml struct to work with
key,: The attribute key to look for
Returns:
Returns the value for the given key, or NULL if none found
References Efreet_Xml::attributes.
void efreet_xml_del (Efreet_Xml * xml)
References Efreet_Xml::attributes, Efreet_Xml::children, FREE, IF_FREE, Efreet_Xml::tag, and Efreet_Xml::text.
Referenced by efreet_menu_parse(), and efreet_xml_new().
int efreet_xml_init (void)
Referenced by efreet_init(), and efreet_menu_init().
Efreet_Xml* efreet_xml_new (const char * file)
References efreet_xml_del().
Referenced by efreet_menu_parse().
int efreet_xml_shutdown (void)
Referenced by efreet_menu_shutdown(), and efreet_shutdown().
Copyright © Enlightenment.org
Efreet Documentation Generated: Sun Oct 5 16:37:23 2008