Efreet: lib/efreet.c File Reference
Home
News
About
Download
Main Page Files Modules Data Structures Index
Support
Contribute
Contact
Tracker
lib/efreet.c File Reference
#include "Efreet.h"
#include "efreet_private.h"
Functions
size_t efreet_array_cat (char *buffer, size_t size, const char *strs[])
EAPI int efreet_init (void)
Initializes the Efreet system.
const char * efreet_lang_country_get (void)
const char * efreet_lang_get (void)
const char * efreet_lang_modifier_get (void)
EAPI int efreet_shutdown (void)
Shuts down Efreet if a balanced number of init/shutdown calls have been made.
Function Documentation
EAPI int efreet_init (void)
Initializes the Efreet system.
Returns:
Returns > 0 if the initialization was successful, 0 otherwise
References efreet_base_init(), efreet_desktop_init(), efreet_icon_init(), efreet_ini_init(), efreet_menu_init(), and efreet_xml_init().
Referenced by efreet_mime_init().
EAPI int efreet_shutdown (void)
Shuts down Efreet if a balanced number of init/shutdown calls have been made.
Returns:
Returns the number of times the init function as been called minus the corresponding init call.
References efreet_base_shutdown(), efreet_desktop_shutdown(), efreet_icon_shutdown(), efreet_ini_shutdown(), efreet_menu_shutdown(), efreet_xml_shutdown(), and IF_FREE.
Referenced by efreet_mime_shutdown().
Copyright © Enlightenment.org
Efreet Documentation Generated: Mon Dec 1 19:57:19 2008