Efreet: lib/efreet_utils.h File Reference
Home
News
About
Download
Main Page Files Modules Data Structures Index
Support
Contribute
Contact
Tracker
lib/efreet_utils.h File Reference
Data Structures
struct Efreet_Event_Desktop_Change
Typedefs
typedef enum Efreet_Desktop_Change Efreet_Desktop_Change
typedef struct
Efreet_Event_Desktop_Change Efreet_Event_Desktop_Change
Enumerations
enum Efreet_Desktop_Change { EFREET_DESKTOP_CHANGE_ADD, EFREET_DESKTOP_CHANGE_REMOVE, EFREET_DESKTOP_CHANGE_UPDATE }
Functions
EAPI Ecore_List * efreet_util_desktop_categories_list (void)
EAPI Ecore_List * efreet_util_desktop_category_list (const char *category)
EAPI Ecore_List * efreet_util_desktop_comment_glob_list (const char *glob)
EAPI Efreet_Desktop * efreet_util_desktop_exec_find (const char *exec)
EAPI Ecore_List * efreet_util_desktop_exec_glob_list (const char *glob)
EAPI Efreet_Desktop * efreet_util_desktop_file_id_find (const char *file_id)
EAPI Efreet_Desktop * efreet_util_desktop_generic_name_find (const char *generic_name)
EAPI Ecore_List * efreet_util_desktop_generic_name_glob_list (const char *glob)
EAPI Ecore_List * efreet_util_desktop_mime_list (const char *mime)
EAPI Efreet_Desktop * efreet_util_desktop_name_find (const char *name)
EAPI Ecore_List * efreet_util_desktop_name_glob_list (const char *glob)
EAPI Efreet_Desktop * efreet_util_desktop_wm_class_find (const char *wmname, const char *wmclass)
EAPI int efreet_util_init (void)
EAPI Ecore_List * efreet_util_menus_find (void)
EAPI const char * efreet_util_path_to_file_id (const char *path)
EAPI int efreet_util_shutdown (void)
Variables
EAPI int EFREET_EVENT_DESKTOP_CHANGE
EAPI int EFREET_EVENT_DESKTOP_LIST_CHANGE
Typedef Documentation
typedef enum Efreet_Desktop_Change Efreet_Desktop_Change
typedef struct Efreet_Event_Desktop_Change Efreet_Event_Desktop_Change
Enumeration Type Documentation
enum Efreet_Desktop_Change
Enumerator:
EFREET_DESKTOP_CHANGE_ADD
EFREET_DESKTOP_CHANGE_REMOVE
EFREET_DESKTOP_CHANGE_UPDATE
Function Documentation
EAPI Ecore_List* efreet_util_desktop_categories_list (void)
Find all desktop categories This list must be freed using ecore_list_destroy()
Returns:
an Ecore_List of category names (const char *)
EAPI Ecore_List* efreet_util_desktop_category_list (const char * category)
Find all desktops in a given category
Note: this returns a pointer to an internal list. Do not add to, remove from, or delete this list.
Parameters:
category the category name
Returns:
a list of desktops
EAPI Ecore_List* efreet_util_desktop_comment_glob_list (const char * glob)
References IF_FREE_LIST, Efreet_Cache_Search_List::list, and Efreet_Cache_Search_List::what.
EAPI Efreet_Desktop* efreet_util_desktop_exec_find (const char * exec)
References Efreet_Util_Desktop::desktop, Efreet_Cache_Search::what1, and Efreet_Cache_Search::what2.
EAPI Ecore_List* efreet_util_desktop_exec_glob_list (const char * glob)
References IF_FREE_LIST, Efreet_Cache_Search_List::list, and Efreet_Cache_Search_List::what.
EAPI Efreet_Desktop* efreet_util_desktop_file_id_find (const char * file_id)
References Efreet_Event_Desktop_Change::change, Efreet_Event_Desktop_Change::current, Efreet_Util_Desktop::desktop, efreet_data_dirs_get(), efreet_data_home_get(), efreet_default_dirs_get(), EFREET_DESKTOP_CHANGE_ADD, efreet_desktop_get(), efreet_desktop_ref(), EFREET_EVENT_DESKTOP_CHANGE, NEW, PATH_MAX, and Efreet_Util_Desktop::priority.
EAPI Efreet_Desktop* efreet_util_desktop_generic_name_find (const char * generic_name)
References Efreet_Util_Desktop::desktop, Efreet_Cache_Search::what1, and Efreet_Cache_Search::what2.
EAPI Ecore_List* efreet_util_desktop_generic_name_glob_list (const char * glob)
References IF_FREE_LIST, Efreet_Cache_Search_List::list, and Efreet_Cache_Search_List::what.
EAPI Ecore_List* efreet_util_desktop_mime_list (const char * mime)
References IF_FREE_LIST, Efreet_Cache_Search_List::list, and Efreet_Cache_Search_List::what.
EAPI Efreet_Desktop* efreet_util_desktop_name_find (const char * name)
References Efreet_Util_Desktop::desktop, Efreet_Cache_Search::what1, and Efreet_Cache_Search::what2.
EAPI Ecore_List* efreet_util_desktop_name_glob_list (const char * glob)
References IF_FREE_LIST, Efreet_Cache_Search_List::list, and Efreet_Cache_Search_List::what.
EAPI Efreet_Desktop* efreet_util_desktop_wm_class_find (const char * wmname, const char * wmclass)
References Efreet_Util_Desktop::desktop, Efreet_Cache_Search::what1, and Efreet_Cache_Search::what2.
EAPI int efreet_util_init (void)
References Efreet_Cache_Fill::dirs, efreet_data_dirs_get(), efreet_data_home_get(), efreet_default_dirs_get(), EFREET_EVENT_DESKTOP_CHANGE, EFREET_EVENT_DESKTOP_LIST_CHANGE, NEW, Efreet_Cache_Fill_Dir::path, and Efreet_Cache_Fill_Dir::priority.
EAPI Ecore_List* efreet_util_menus_find (void)
Returns a list of .menu files found in the various config dirs.
Returns:
An ecore list of menu file paths (const char *). This must be freed with ecore_list_destroy().
References efreet_config_dirs_get(), and efreet_config_home_get().
EAPI const char* efreet_util_path_to_file_id (const char * path)
Referenced by efreet_menu_desktop_insert().
EAPI int efreet_util_shutdown (void)
References Efreet_Cache_Fill::current, Efreet_Cache_Fill::dirs, Efreet_Cache_Fill::files, IF_FREE_HASH, and IF_FREE_LIST.
Variable Documentation
EAPI int EFREET_EVENT_DESKTOP_CHANGE
Referenced by efreet_util_desktop_file_id_find(), and efreet_util_init().
EAPI int EFREET_EVENT_DESKTOP_LIST_CHANGE
Referenced by efreet_util_init().
Copyright © Enlightenment.org
Efreet Documentation Generated: Mon Dec 1 19:57:21 2008