Efreet: Efreet_Icon: The FDO Icon Theme
Home
News
About
Download
Main Page Files Modules Data Structures Index
Support
Contribute
Contact
Tracker
Efreet_Icon: The FDO Icon Theme
Detailed Description
Specification functions and structures
Data Structures
struct Efreet_Icon
Contains all the information about a given icon.
struct Efreet_Icon_Point
Stores an x, y point.
struct Efreet_Icon_Theme
contains all of the known information about a given theme
struct Efreet_Icon_Theme_Directory
Contains all the information about a sub-directory of a theme.
Typedefs
typedef struct Efreet_Icon Efreet_Icon
typedef struct Efreet_Icon_Point Efreet_Icon_Point
typedef struct Efreet_Icon_Theme Efreet_Icon_Theme
typedef struct
Efreet_Icon_Theme_Directory Efreet_Icon_Theme_Directory
Enumerations
enum Efreet_Icon_Size_Type { EFREET_ICON_SIZE_TYPE_NONE, EFREET_ICON_SIZE_TYPE_FIXED, EFREET_ICON_SIZE_TYPE_SCALABLE, EFREET_ICON_SIZE_TYPE_THRESHOLD }
enum Efreet_Icon_Theme_Context {
EFREET_ICON_THEME_CONTEXT_NONE, EFREET_ICON_THEME_CONTEXT_ACTIONS, EFREET_ICON_THEME_CONTEXT_DEVICES, EFREET_ICON_THEME_CONTEXT_FILESYSTEMS,
EFREET_ICON_THEME_CONTEXT_MIMETYPES
}
Functions
EAPI void efreet_icon_extension_add (const char *ext)
Adds the given extension to the list of possible icon extensions.
EAPI Ecore_List * efreet_icon_extra_list_get (void)
Gets the list of all extra directories to look for icons. These directories are used to look for icons after looking in the user icon dir and before looking in standard system directories. The order of search is from first to last directory in this list. the strings in the list should be created with ecore_string_instance().
EAPI Efreet_Icon * efreet_icon_find (const char *theme_name, const char *icon, unsigned int size)
Retrieves all of the information about the given icon.
EAPI void efreet_icon_free (Efreet_Icon *icon)
Free's the given icon and all its internal data.
EAPI char * efreet_icon_list_find (const char *theme_name, Ecore_List *icons, unsigned int size)
Retrieves all of the information about the first found icon in the list.
EAPI char * efreet_icon_path_find (const char *theme_name, const char *icon, unsigned int size)
Retrives the path to the given icon.
EAPI Efreet_Icon_Theme * efreet_icon_theme_find (const char *theme_name)
Tries to get the icon theme structure for the given theme name.
EAPI Ecore_List * efreet_icon_theme_list_get (void)
Retrieves all of the non-hidden icon themes available on the system. The returned list must be freed. Do not free the list data.
EAPI const char * efreet_icon_user_dir_get (void)
Typedef Documentation
typedef struct Efreet_Icon Efreet_Icon
Efreet_Icon
typedef struct Efreet_Icon_Point Efreet_Icon_Point
Efreet_Point
typedef struct Efreet_Icon_Theme Efreet_Icon_Theme
Efreet_Icon_Theme
typedef struct Efreet_Icon_Theme_Directory Efreet_Icon_Theme_Directory
Efreet_Icon_Theme_Directory
Enumeration Type Documentation
enum typedef enum Efreet_Icon_Size_Type Efreet_Icon_Size_Type
The possible size types for an icon directory
Efreet_Icon_Size_Type
Enumerator:
EFREET_ICON_SIZE_TYPE_NONE
EFREET_ICON_SIZE_TYPE_FIXED
EFREET_ICON_SIZE_TYPE_SCALABLE
EFREET_ICON_SIZE_TYPE_THRESHOLD
enum typedef enum Efreet_Icon_Theme_Context Efreet_Icon_Theme_Context
The possible contexts for an icon directory
Efreet_icon_Theme_Context
Enumerator:
EFREET_ICON_THEME_CONTEXT_NONE
EFREET_ICON_THEME_CONTEXT_ACTIONS
EFREET_ICON_THEME_CONTEXT_DEVICES
EFREET_ICON_THEME_CONTEXT_FILESYSTEMS
EFREET_ICON_THEME_CONTEXT_MIMETYPES
Function Documentation
EAPI void efreet_icon_extension_add (const char * ext)
Adds the given extension to the list of possible icon extensions.
Parameters:
ext,: The extension to add to the list of checked extensions
Returns:
Returns no value.
EAPI Ecore_List* efreet_icon_extra_list_get (void)
Gets the list of all extra directories to look for icons. These directories are used to look for icons after looking in the user icon dir and before looking in standard system directories. The order of search is from first to last directory in this list. the strings in the list should be created with ecore_string_instance().
Returns:
Returns a list of strings that are paths to other icon directories
EAPI Efreet_Icon* efreet_icon_find (const char * theme_name, const char * icon, unsigned int size)
Retrieves all of the information about the given icon.
Parameters:
theme,: The icon theme to look for
icon,: The icon to look for
size,: The icon size to look for
Returns:
Returns the Efreet_Icon structure representing this icon or NULL if the icon is not found
References efreet_icon_path_find().
EAPI void efreet_icon_free (Efreet_Icon * icon)
Free's the given icon and all its internal data.
Parameters:
icon,: The Efreet_Icon to cleanup
Returns:
Returns no value.
References attach_points, FREE, IF_FREE, IF_FREE_LIST, name, path, and ref_count.
EAPI char* efreet_icon_list_find (const char * theme_name, Ecore_List * icons, unsigned int size)
Retrieves all of the information about the first found icon in the list.
Parameters:
theme_name,: The icon theme to look for
icons,: List of icons to look for
size; The icon size to look for
Returns:
Returns the path representing first found icon or NULL if none of the icons are found
Note:
This function will search the given theme for all icons before falling back. This is useful when searching for mimetype icons.
References NON_EXISTING.
Referenced by efreet_mime_type_icon_get().
EAPI char* efreet_icon_path_find (const char * theme_name, const char * icon, unsigned int size)
Retrives the path to the given icon.
Parameters:
theme_name,: The icon theme to look for
icon,: The icon to look for
size; The icon size to look for
Returns:
Returns the path to the given icon or NULL if none found
References FREE, and NON_EXISTING.
Referenced by efreet_icon_find().
EAPI Efreet_Icon_Theme* efreet_icon_theme_find (const char * theme_name)
Tries to get the icon theme structure for the given theme name.
Parameters:
theme_name,: The theme to look for
Returns:
Returns the icon theme related to the given theme name or NULL if none exists.
EAPI Ecore_List* efreet_icon_theme_list_get (void)
Retrieves all of the non-hidden icon themes available on the system. The returned list must be freed. Do not free the list data.
Returns:
Returns a list of Efreet_Icon structs for all the non-hidden icon themes
References Efreet_Icon_Theme::fake, Efreet_Icon_Theme::hidden, and Efreet_Icon_Theme::name.
EAPI const char* efreet_icon_user_dir_get (void)
References efreet_data_home_get().
Copyright © Enlightenment.org
Efreet Documentation Generated: Sun Oct 5 16:37:23 2008