Efreet: Efreet_Menu: The FDO Desktop Menu Specification
Home
News
About
Download
Main Page Files Modules Data Structures Index
Support
Contribute
Contact
Tracker
Efreet_Menu: The FDO Desktop Menu Specification
Detailed Description
functions and structures
Data Structures
struct Efreet_Menu
Typedefs
typedef struct Efreet_Menu Efreet_Menu
typedef enum Efreet_Menu_Entry_Type Efreet_Menu_Entry_Type
Enumerations
enum Efreet_Menu_Entry_Type { EFREET_MENU_ENTRY_MENU, EFREET_MENU_ENTRY_DESKTOP, EFREET_MENU_ENTRY_SEPARATOR, EFREET_MENU_ENTRY_HEADER }
Functions
EAPI int efreet_menu_desktop_insert (Efreet_Menu *menu, Efreet_Desktop *desktop, int pos)
Insert a desktop element in a menu structure. Only accepts desktop files in default directories.
EAPI int efreet_menu_desktop_remove (Efreet_Menu *menu, Efreet_Desktop *desktop)
Remove a desktop element in a menu structure. Only accepts desktop files in default directories.
EAPI void efreet_menu_dump (Efreet_Menu *menu, const char *indent)
Dumps the contents of the menu to the command line.
EAPI void efreet_menu_file_set (const char *file)
EAPI void efreet_menu_free (Efreet_Menu *menu)
EAPI Efreet_Menu * efreet_menu_get (void)
Creates the default menu representation.
EAPI int efreet_menu_kde_legacy_init (void)
Initialize legacy kde support. This function blocks while the kde-config script is run.
EAPI Efreet_Menu * efreet_menu_new (void)
EAPI Efreet_Menu * efreet_menu_parse (const char *path)
Parses the given .menu file and creates the menu representation.
EAPI int efreet_menu_save (Efreet_Menu *menu, const char *path)
Saves the menu to file.
Typedef Documentation
typedef struct Efreet_Menu Efreet_Menu
Efreet_Menu
typedef enum Efreet_Menu_Entry_Type Efreet_Menu_Entry_Type
Efreet_Menu_Entry_Type
Enumeration Type Documentation
enum Efreet_Menu_Entry_Type
The type of entry
Enumerator:
EFREET_MENU_ENTRY_MENU
EFREET_MENU_ENTRY_DESKTOP
EFREET_MENU_ENTRY_SEPARATOR
EFREET_MENU_ENTRY_HEADER
Function Documentation
EAPI int efreet_menu_desktop_insert (Efreet_Menu * menu, Efreet_Desktop * desktop, int pos)
Insert a desktop element in a menu structure. Only accepts desktop files in default directories.
Parameters:
menu,: The menu to work with
desktop,: The desktop to insert
pos,: The position to place the new desktop
Returns:
Returns 1 on success, 0 on failure
References desktop, efreet_desktop_ref(), EFREET_MENU_ENTRY_DESKTOP, efreet_menu_free(), efreet_util_path_to_file_id(), entries, icon, Efreet_Desktop::icon, id, Efreet_Desktop::name, name, Efreet_Desktop::orig_path, and type.
EAPI int efreet_menu_desktop_remove (Efreet_Menu * menu, Efreet_Desktop * desktop)
Remove a desktop element in a menu structure. Only accepts desktop files in default directories.
Parameters:
menu,: The menu to work with
desktop,: The desktop to remove
Returns:
Returns 1 on success, 0 on failure
References efreet_menu_free(), and entries.
EAPI void efreet_menu_dump (Efreet_Menu * menu, const char * indent)
Dumps the contents of the menu to the command line.
Parameters:
menu,: The menu to work with
menu,: The menu to work with
indent,: The indent level to print the menu at
Returns:
Returns no value
References efreet_menu_dump(), EFREET_MENU_ENTRY_DESKTOP, EFREET_MENU_ENTRY_HEADER, EFREET_MENU_ENTRY_MENU, EFREET_MENU_ENTRY_SEPARATOR, entries, FREE, icon, name, and type.
Referenced by efreet_menu_dump().
EAPI void efreet_menu_file_set (const char * file)
References IF_FREE.
EAPI void efreet_menu_free (Efreet_Menu * menu)
References desktop, efreet_desktop_free(), entries, FREE, icon, id, IF_FREE_LIST, IF_RELEASE, and name.
Referenced by efreet_menu_desktop_insert(), and efreet_menu_desktop_remove().
EAPI Efreet_Menu* efreet_menu_get (void)
Creates the default menu representation.
Returns:
Returns the Efreet_Menu_Internal representation of the default menu or NULL if none found
References efreet_config_dirs_get(), efreet_config_home_get(), efreet_menu_parse(), and PATH_MAX.
EAPI int efreet_menu_kde_legacy_init (void)
Initialize legacy kde support. This function blocks while the kde-config script is run.
Returns:
Returns no value
References efreet_menu_kde_legacy_dirs, IF_FREE_LIST, and PATH_MAX.
EAPI Efreet_Menu* efreet_menu_new (void)
References EFREET_MENU_ENTRY_MENU, and type.
EAPI Efreet_Menu* efreet_menu_parse (const char * path)
Parses the given .menu file and creates the menu representation.
Parameters:
path,: The path of the menu to load
Returns:
Returns the Efreet_Menu_Internal representation on success or NULL on failure
References efreet_config_dirs_get(), efreet_xml_del(), efreet_xml_new(), IF_FREE_HASH, and Efreet_Xml::tag.
Referenced by efreet_menu_get().
EAPI int efreet_menu_save (Efreet_Menu * menu, const char * path)
Saves the menu to file.
Parameters:
menu,: The menu to work with
path,: The path where the menu should be saved
Returns:
Returns 1 on success, 0 on failure
Copyright © Enlightenment.org
Efreet Documentation Generated: Mon Dec 1 19:57:21 2008