Efreet: Efreet_Base: The XDG Base Directory Specification
Home
News
About
Download
Main Page Files Modules Data Structures Index
Support
Contribute
Contact
Tracker
Efreet_Base: The XDG Base Directory Specification
Detailed Description
functions
Functions
EAPI const char * efreet_cache_home_get (void)
Retrieves the XDG Cache Home directory.
EAPI Ecore_List * efreet_config_dirs_get (void)
Returns the Ecore_List of prefernece oredred extra config directories.
EAPI const char * efreet_config_home_get (void)
Retrieves the XDG Config Home directory.
EAPI Ecore_List * efreet_data_dirs_get (void)
Returns the Ecore_List of prefernece oredred extra data directories.
EAPI const char * efreet_data_home_get (void)
Retrieves the XDG Data Home directory.
Function Documentation
EAPI const char* efreet_cache_home_get (void)
Retrieves the XDG Cache Home directory.
Returns:
Returns the XDG Cache Home directory
EAPI Ecore_List* efreet_config_dirs_get (void)
Returns the Ecore_List of prefernece oredred extra config directories.
Returns:
Returns the Ecore_List of preference ordered extra config directories
Note:
The returned list is static inside Efreet. If you add/remove from the list then the next call to efreet_config_dirs_get() will return your modified values. DO NOT free this list.
Referenced by efreet_menu_get(), efreet_menu_parse(), and efreet_util_menus_find().
EAPI const char* efreet_config_home_get (void)
Retrieves the XDG Config Home directory.
Returns:
Returns the XDG Config Home directory
Referenced by efreet_menu_get(), and efreet_util_menus_find().
EAPI Ecore_List* efreet_data_dirs_get (void)
Returns the Ecore_List of prefernece oredred extra data directories.
Returns:
Returns the Ecore_List of preference ordered extra data directories
Note:
The returned list is static inside Efreet. If you add/remove from the list then the next call to efreet_data_dirs_get() will return your modified values. DO NOT free this list.
Referenced by efreet_util_desktop_file_id_find(), and efreet_util_init().
EAPI const char* efreet_data_home_get (void)
Retrieves the XDG Data Home directory.
Returns:
Returns the XDG Data Home directory
Referenced by efreet_icon_user_dir_get(), efreet_trash_dir_get(), efreet_util_desktop_file_id_find(), and efreet_util_init().
Copyright © Enlightenment.org
Efreet Documentation Generated: Sun Oct 5 16:37:23 2008